// main exports
export { default as Client } from './src/Client';
export { default as Enums } from './enums/Enums';

// types and interfaces
export * from './resources/structs';

// endpoints
export { default as Endpoints } from './resources/Endpoints';

// exceptions
export { default as AuthenticationMissingError } from './src/exceptions/AuthenticationMissingError';
export { default as CreativeIslandNotFoundError } from './src/exceptions/CreativeIslandNotFoundError';
export { default as CreatorCodeNotFoundError } from './src/exceptions/CreatorCodeNotFoundError';
export { default as DuplicateFriendshipError } from './src/exceptions/DuplicateFriendshipError';
export { default as EpicgamesAPIError } from './src/exceptions/EpicgamesAPIError';
export { default as EventTimeoutError } from './src/exceptions/EventTimeoutError';
export { default as FriendNotFoundError } from './src/exceptions/FriendNotFoundError';
export { default as FriendshipRequestAlreadySentError } from './src/exceptions/FriendshipRequestAlreadySentError';
export { default as InviteeFriendshipRequestLimitExceededError } from './src/exceptions/InviteeFriendshipRequestLimitExceededError';
export { default as InviteeFriendshipSettingsError } from './src/exceptions/InviteeFriendshipSettingsError';
export { default as InviteeFriendshipsLimitExceededError } from './src/exceptions/InviteeFriendshipsLimitExceededError';
export { default as InviterFriendshipsLimitExceededError } from './src/exceptions/InviterFriendshipsLimitExceededError';
export { default as MatchNotFoundError } from './src/exceptions/MatchNotFoundError';
export { default as OfferNotFoundError } from './src/exceptions/OfferNotFoundError';
export { default as PartyAlreadyJoinedError } from './src/exceptions/PartyAlreadyJoinedError';
export { default as PartyInvitationExpiredError } from './src/exceptions/PartyInvitationExpiredError';
export { default as PartyMaxSizeReachedError } from './src/exceptions/PartyMaxSizeReachedError';
export { default as PartyMemberNotFoundError } from './src/exceptions/PartyMemberNotFoundError';
export { default as PartyNotFoundError } from './src/exceptions/PartyNotFoundError';
export { default as PartyPermissionError } from './src/exceptions/PartyPermissionError';
export { default as SendMessageError } from './src/exceptions/SendMessageError';
export { default as StatsPrivacyError } from './src/exceptions/StatsPrivacyError';
export { default as UserNotFoundError } from './src/exceptions/UserNotFoundError';
export { default as XMPPConnectionError } from './src/exceptions/XMPPConnectionError';
export { default as XMPPConnectionTimeoutError } from './src/exceptions/XMPPConnectionTimeoutError';

// structures
export { default as Avatar } from './src/structures/Avatar';
export { default as BaseMessage } from './src/structures/BaseMessage';
export { default as CreatorCode } from './src/structures/CreatorCode';
export { default as EpicgamesServerStatus } from './src/structures/EpicgamesServerStatus';
export { default as EpicgamesServerStatusComponent } from './src/structures/EpicgamesServerStatusComponent';
export { default as EpicgamesServerStatusIncident } from './src/structures/EpicgamesServerStatusIncident';
export { default as EpicgamesServerStatusScheduledMainteance } from './src/structures/EpicgamesServerStatusScheduledMainteance';
export { default as EventTokens } from './src/structures/EventTokens';
export { default as FortniteServerStatus } from './src/structures/FortniteServerStatus';
export { default as GlobalProfile } from './src/structures/GlobalProfile';
export { default as Image } from './src/structures/Image';
export { default as NewsMessage } from './src/structures/NewsMessage';
export { default as NewsMessageVideo } from './src/structures/NewsMessageVideo';
export { default as RadioStation } from './src/structures/RadioStation';
export { default as Stats } from './src/structures/Stats';
export { default as Tournament } from './src/structures/Tournament';
export { default as TournamentWindow } from './src/structures/TournamentWindow';
export { default as BaseFriendMessage } from './src/structures/friend/BaseFriendMessage';
export { default as BasePendingFriend } from './src/structures/friend/BasePendingFriend';
export { default as Friend } from './src/structures/friend/Friend';
export { default as FriendPresence } from './src/structures/friend/FriendPresence';
export { default as IncomingPendingFriend } from './src/structures/friend/IncomingPendingFriend';
export { default as OutgoingPendingFriend } from './src/structures/friend/OutgoingPendingFriend';
export { default as ReceivedFriendMessage } from './src/structures/friend/ReceivedFriendMessage';
export { default as SentFriendMessage } from './src/structures/friend/SentFriendMessage';
export { default as BasePartyInvitation } from './src/structures/party/BasePartyInvitation';
export { default as BasePartyJoinRequest } from './src/structures/party/BasePartyJoinRequest';
export { default as ClientParty } from './src/structures/party/ClientParty';
export { default as ClientPartyMember } from './src/structures/party/ClientPartyMember';
export { default as ClientPartyMemberMeta } from './src/structures/party/ClientPartyMemberMeta';
export { default as ClientPartyMeta } from './src/structures/party/ClientPartyMeta';
export { default as Party } from './src/structures/party/Party';
export { default as PartyChat } from './src/structures/party/PartyChat';
export { default as PartyMember } from './src/structures/party/PartyMember';
export { default as PartyMemberConfirmation } from './src/structures/party/PartyMemberConfirmation';
export { default as PartyMemberMeta } from './src/structures/party/PartyMemberMeta';
export { default as PartyMessage } from './src/structures/party/PartyMessage';
export { default as PartyMeta } from './src/structures/party/PartyMeta';
export { default as PresenceParty } from './src/structures/party/PresenceParty';
export { default as ReceivedPartyInvitation } from './src/structures/party/ReceivedPartyInvitation';
export { default as ReceivedPartyJoinRequest } from './src/structures/party/ReceivedPartyJoinRequest';
export { default as SentPartyInvitation } from './src/structures/party/SentPartyInvitation';
export { default as SentPartyJoinRequest } from './src/structures/party/SentPartyJoinRequest';
export { default as STWHero } from './src/structures/stw/STWHero';
export { default as STWHeroLoadout } from './src/structures/stw/STWHeroLoadout';
export { default as STWItem } from './src/structures/stw/STWItem';
export { default as STWLocker } from './src/structures/stw/STWLocker';
export { default as STWMeleeWeaponSchematic } from './src/structures/stw/STWMeleeWeaponSchematic';
export { default as STWNewsMessage } from './src/structures/stw/STWNewsMessage';
export { default as STWProfile } from './src/structures/stw/STWProfile';
export { default as STWRangedWeaponSchematic } from './src/structures/stw/STWRangedWeaponSchematic';
export { default as STWResource } from './src/structures/stw/STWResource';
export { default as STWSchematic } from './src/structures/stw/STWSchematic';
export { default as STWStats } from './src/structures/stw/STWStats';
export { default as STWSurvivor } from './src/structures/stw/STWSurvivor';
export { default as STWTeamPerk } from './src/structures/stw/STWTeamPerk';
export { default as STWTrapSchematic } from './src/structures/stw/STWTrapSchematic';
export { default as STWWeaponSchematic } from './src/structures/stw/STWWeaponSchematic';
export { default as BlockedUser } from './src/structures/user/BlockedUser';
export { default as ClientUser } from './src/structures/user/ClientUser';
export { default as User } from './src/structures/user/User';
export { default as UserSearchResult } from './src/structures/user/UserSearchResult';
